name: vending_machine
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  intl: ^0.17.0

  #Snack
  another_flushbar: ^1.10.29
  
  #State Management
  flutter_bloc: ^8.1.3

  #Equatable
  equatable: ^2.0.5

  #Svg image
  flutter_svg: ^1.1.1+1

  #Dependency Injection
  get_it: ^7.2.0

  #Page transition
  page_transition: ^2.0.9

  #Local storage
  shared_preferences: ^2.0.15

  #Network image
  cached_network_image: ^3.2.3

  #Dialog
  adaptive_dialog: ^1.8.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true
